### PR TITLE
Make it possible to report only total descriptor count (--only-total)

### PR DESCRIPTION
**Pull request by michaelklishin**
As discussed in #5.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lukebakken @the-mikedavis macOS and Linux implementations of `--only-total` now work as expected. I don't expect my changes to the Windows part to be correct, though :)

**Comment by michaelklishin** [comment]
@lukebakken @the-mikedavis macOS and Linux implementations of `--only-total` now work as expected. Now I need your help with Windows :)

**Review by the-mikedavis — COMMENTED** [review]
What do you think about introducing a new function for getting just the total instead? `list` can also calculate the total but it would remove the need to allocate any `Vec`s. For Windows we will want to use totally different set of calls to get only the total count anyways:

```rust
// impl for #[cfg(target_os = "windows")]
impl FdList {
    pub fn list(pid: Pid) -> Result<ProcStats, FshcError> {
        // * Get the full set of handles with `NtQuerySystemInformation`
        // * Determine the file handle object type id
        // * Count the file handles and total handles for the given `pid`
    }

    pub fn total(pid: Pid) -> Result<ProcStats, FshcError> {
        // Get the total handle count for the pid directly with `GetProcessHandleCount`,
        // see <https://github.com/rabbitmq/fshc/blob/4b2ae78c2525183bd80e1952b4c0038db4c71511/src/fds/windows.rs#L19-L25>
    }
}
```

There would be some duplicated code for Linux & macOS but it should only be a few lines.

**Comment by michaelklishin** [comment]
@the-mikedavis SGTM

**Comment by michaelklishin** [comment]
@the-mikedavis for example, `list_total` and `list_by_type`. I can make the change for Linux and macOS if you agree with the names.

**Comment by michaelklishin** [comment]
@the-mikedavis done for macOS and Linux. I have adjusted the API for Windows in a very naive way, feel free to replace it as you see fit.

**Pull request merged**
